version: '3.9'

services:
  api:
    container_name: node
    build: .
    restart: always
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      mongo_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
  mongo_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo_db:/data/db
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
